//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<int> ProfessionID { get; set; }
        public Nullable<int> Course { get; set; }
        public Nullable<int> FacultyID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public byte[] Avatar { get; set; }
        public bool IsValidated { get; set; }
    }
}
